/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicComplianceCheckRouteImport } from './routes/api/public/compliance-check'

const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicComplianceCheckRoute =
  ApiPublicComplianceCheckRouteImport.update({
    id: '/api/public/compliance-check',
    path: '/api/public/compliance-check',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rules': typeof RulesRoute
  '/api/public/compliance-check': typeof ApiPublicComplianceCheckRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rules': typeof RulesRoute
  '/api/public/compliance-check': typeof ApiPublicComplianceCheckRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rules': typeof RulesRoute
  '/api/public/compliance-check': typeof ApiPublicComplianceCheckRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/rules' | '/api/public/compliance-check'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/rules' | '/api/public/compliance-check'
  id: '__root__' | '/' | '/rules' | '/api/public/compliance-check'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RulesRoute: typeof RulesRoute
  ApiPublicComplianceCheckRoute: typeof ApiPublicComplianceCheckRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/compliance-check': {
      id: '/api/public/compliance-check'
      path: '/api/public/compliance-check'
      fullPath: '/api/public/compliance-check'
      preLoaderRoute: typeof ApiPublicComplianceCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RulesRoute: RulesRoute,
  ApiPublicComplianceCheckRoute: ApiPublicComplianceCheckRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
